// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="denose_denose,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z015-clg485-2,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.533500,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=312,HLS_SYN_LUT=1341,HLS_VERSION=2023_2}" *)

module denose (
        ap_clk,
        ap_rst,
        in_data,
        in_valid,
        in_last,
        out_ready,
        out_data,
        out_valid,
        out_last,
        in_ready
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input  [7:0] in_data;
input  [0:0] in_valid;
input  [0:0] in_last;
input  [0:0] out_ready;
output  [7:0] out_data;
output  [0:0] out_valid;
output  [0:0] out_last;
output  [0:0] in_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_denoise_fu_114_ap_start;
wire    grp_denoise_fu_114_ap_done;
wire    grp_denoise_fu_114_ap_idle;
wire    grp_denoise_fu_114_ap_ready;
wire   [31:0] grp_denoise_fu_114_ap_return_0;
wire   [7:0] grp_denoise_fu_114_ap_return_1;
wire   [31:0] grp_denoise_fu_114_ap_return_2;
wire   [31:0] grp_denoise_fu_114_ap_return_3;
reg    grp_denoise_fu_114_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_denoise_fu_114_ap_start_reg = 1'b0;
end

denose_denoise grp_denoise_fu_114(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_denoise_fu_114_ap_start),
    .ap_done(grp_denoise_fu_114_ap_done),
    .ap_idle(grp_denoise_fu_114_ap_idle),
    .ap_ready(grp_denoise_fu_114_ap_ready),
    .in_data_val(in_data),
    .in_valid(in_valid),
    .in_last(in_last),
    .out_ready(out_ready),
    .ap_return_0(grp_denoise_fu_114_ap_return_0),
    .ap_return_1(grp_denoise_fu_114_ap_return_1),
    .ap_return_2(grp_denoise_fu_114_ap_return_2),
    .ap_return_3(grp_denoise_fu_114_ap_return_3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_denoise_fu_114_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_denoise_fu_114_ap_start_reg <= 1'b1;
        end else if ((grp_denoise_fu_114_ap_ready == 1'b1)) begin
            grp_denoise_fu_114_ap_start_reg <= 1'b0;
        end
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_denoise_fu_114_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((grp_denoise_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_denoise_fu_114_ap_start = grp_denoise_fu_114_ap_start_reg;

assign in_ready = grp_denoise_fu_114_ap_return_0[0:0];

assign out_data = grp_denoise_fu_114_ap_return_1;

assign out_last = grp_denoise_fu_114_ap_return_2[0:0];

assign out_valid = grp_denoise_fu_114_ap_return_3[0:0];

endmodule //denose
