// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module denose_denoise (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_data_val,
        in_valid,
        in_last,
        out_ready,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_data_val;
input  [0:0] in_valid;
input  [0:0] in_last;
input  [0:0] out_ready;
output  [31:0] ap_return_0;
output  [7:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] pending_data;
reg   [0:0] pending_last;
reg   [0:0] pending_valid;
reg   [31:0] op_idx;
reg   [31:0] wr;
reg   [31:0] idx;
reg   [0:0] first_frame;
reg   [9:0] q_address0;
reg    q_ce0;
wire   [7:0] q_q0;
reg   [9:0] q_address1;
reg    q_ce1;
reg    q_we1;
wire   [7:0] q_q1;
reg   [8:0] rear_frame_address0;
reg    rear_frame_ce0;
reg    rear_frame_we0;
wire   [7:0] rear_frame_q0;
reg   [7:0] reg_317;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [0:0] in_last_read_read_fu_122_p2;
wire   [31:0] pending_last_load_cast_fu_330_p1;
reg   [31:0] pending_last_load_cast_reg_1193;
wire   [31:0] out_valid_0_fu_338_p1;
reg   [31:0] out_valid_0_reg_1198;
wire   [31:0] zext_ln90_fu_354_p1;
reg   [31:0] zext_ln90_reg_1203;
wire   [0:0] and_ln92_fu_358_p2;
wire   [31:0] add_ln101_fu_390_p2;
reg   [31:0] add_ln101_reg_1220;
wire   [9:0] r513_2_fu_436_p3;
reg   [9:0] r513_2_reg_1226;
wire   [9:0] r512_1_fu_468_p3;
reg   [9:0] r512_1_reg_1231;
wire   [9:0] r258_2_fu_500_p3;
reg   [9:0] r258_2_reg_1236;
wire   [9:0] r256_2_fu_564_p3;
reg   [9:0] r256_2_reg_1241;
wire   [9:0] r2_1_fu_596_p3;
reg   [9:0] r2_1_reg_1246;
wire   [9:0] r1_2_fu_628_p3;
reg   [9:0] r1_2_reg_1251;
wire   [8:0] trunc_ln110_fu_640_p1;
reg   [8:0] trunc_ln110_reg_1259;
wire   [0:0] icmp_ln112_fu_662_p2;
reg   [0:0] icmp_ln112_reg_1264;
wire   [0:0] icmp_ln117_fu_714_p2;
reg   [0:0] icmp_ln117_reg_1269;
wire   [0:0] and_ln116_1_fu_794_p2;
reg   [0:0] and_ln116_1_reg_1274;
wire   [0:0] has_output_1_fu_800_p3;
reg   [0:0] has_output_1_reg_1279;
wire   [0:0] or_ln125_fu_826_p2;
reg   [0:0] or_ln125_reg_1283;
wire   [0:0] next_last_fu_852_p2;
reg   [0:0] next_last_reg_1297;
wire   [9:0] select_ln110_fu_863_p3;
reg   [9:0] select_ln110_reg_1307;
wire   [0:0] or_ln130_fu_871_p2;
reg   [0:0] or_ln130_reg_1312;
reg   [7:0] q_load_reg_1318;
wire    ap_CS_fsm_state2;
reg   [7:0] next_data_reg_1323;
reg   [7:0] q_load_1_reg_1328;
reg   [7:0] q_load_3_reg_1343;
wire   [8:0] tmp_fu_909_p2;
reg   [8:0] tmp_reg_1368;
wire   [9:0] tmp154_fu_946_p2;
reg   [9:0] tmp154_reg_1373;
wire    ap_CS_fsm_state5;
wire   [9:0] add_ln133_3_fu_962_p2;
reg   [9:0] add_ln133_3_reg_1378;
reg   [0:0] ap_phi_mux_pending_last_flag_1_phi_fu_253_p4;
reg   [0:0] pending_last_flag_1_reg_250;
wire    ap_CS_fsm_state6;
wire   [0:0] next_last_1_fu_1051_p2;
reg   [0:0] ap_phi_mux_pending_last_new_1_phi_fu_264_p4;
reg   [0:0] pending_last_new_1_reg_260;
reg   [0:0] ap_phi_mux_pending_valid_new_1_phi_fu_275_p4;
reg   [0:0] pending_valid_new_1_reg_271;
reg   [0:0] ap_phi_mux_pending_last_flag_2_phi_fu_286_p4;
reg   [0:0] pending_last_flag_2_reg_283;
reg   [0:0] ap_phi_mux_pending_last_new_2_phi_fu_297_p4;
reg   [0:0] pending_last_new_2_reg_293;
reg   [0:0] ap_phi_mux_pending_valid_new_2_phi_fu_309_p4;
reg   [0:0] pending_valid_new_2_reg_305;
wire   [63:0] zext_ln137_fu_836_p1;
wire   [63:0] zext_ln150_fu_847_p1;
wire   [63:0] zext_ln133_fu_858_p1;
wire   [63:0] zext_ln134_fu_877_p1;
wire   [63:0] zext_ln135_1_fu_881_p1;
wire   [63:0] zext_ln136_1_fu_885_p1;
wire   [63:0] zext_ln138_1_fu_889_p1;
wire   [63:0] zext_ln139_fu_893_p1;
wire   [63:0] zext_ln140_1_fu_897_p1;
wire   [63:0] zext_ln128_fu_968_p1;
wire   [63:0] zext_ln161_fu_1063_p1;
wire   [63:0] zext_ln163_fu_1077_p1;
wire   [0:0] icmp_ln162_fu_1067_p2;
wire   [7:0] next_data_4_fu_1038_p3;
wire   [31:0] select_ln167_fu_1087_p3;
wire   [31:0] select_ln183_fu_1116_p3;
wire   [31:0] add_ln181_fu_1100_p2;
wire   [0:0] xor_ln90_fu_342_p2;
wire   [0:0] or_ln90_fu_348_p2;
wire   [31:0] r514_fu_376_p2;
wire   [0:0] tmp_1_fu_382_p3;
wire   [9:0] trunc_ln101_1_fu_396_p1;
wire   [9:0] trunc_ln101_2_fu_400_p1;
wire   [31:0] r513_fu_412_p2;
wire   [9:0] trunc_ln101_fu_372_p1;
wire   [0:0] tmp_2_fu_422_p3;
wire   [9:0] r513_1_fu_430_p2;
wire   [9:0] trunc_ln102_fu_418_p1;
wire   [31:0] r512_fu_444_p2;
wire   [0:0] tmp_3_fu_454_p3;
wire   [9:0] add_ln103_fu_462_p2;
wire   [9:0] trunc_ln103_fu_450_p1;
wire   [31:0] r258_fu_476_p2;
wire   [0:0] tmp_4_fu_486_p3;
wire   [9:0] r258_1_fu_494_p2;
wire   [9:0] trunc_ln104_fu_482_p1;
wire   [31:0] r257_fu_508_p2;
wire   [0:0] tmp_5_fu_518_p3;
wire   [9:0] add_ln105_fu_526_p2;
wire   [9:0] trunc_ln105_fu_514_p1;
wire   [31:0] r256_fu_540_p2;
wire   [0:0] tmp_6_fu_550_p3;
wire   [9:0] r256_1_fu_558_p2;
wire   [9:0] trunc_ln106_fu_546_p1;
wire   [31:0] r2_fu_572_p2;
wire   [0:0] tmp_7_fu_582_p3;
wire   [9:0] add_ln107_fu_590_p2;
wire   [9:0] trunc_ln107_fu_578_p1;
wire   [31:0] r1_fu_604_p2;
wire   [0:0] tmp_8_fu_614_p3;
wire   [9:0] r1_1_fu_622_p2;
wire   [9:0] trunc_ln108_fu_610_p1;
wire   [0:0] icmp_ln110_fu_644_p2;
wire   [0:0] icmp_ln110_1_fu_650_p2;
wire   [15:0] tmp_9_fu_682_p4;
wire   [0:0] icmp_ln116_fu_676_p2;
wire   [0:0] icmp_ln116_1_fu_692_p2;
wire   [6:0] tmp_10_fu_704_p4;
wire   [31:0] add_ln117_fu_720_p2;
wire   [0:0] icmp_ln117_1_fu_726_p2;
wire   [15:0] tmp_11_fu_742_p4;
wire   [0:0] icmp_ln121_fu_752_p2;
wire   [0:0] and_ln110_fu_656_p2;
wire   [31:0] output_idx_1_fu_668_p3;
wire   [31:0] output_idx_2_fu_764_p3;
wire   [0:0] has_output_fu_758_p2;
wire   [0:0] and_ln110_1_fu_782_p2;
wire   [0:0] and_ln116_fu_698_p2;
wire   [0:0] xor_ln110_fu_788_p2;
wire   [0:0] or_ln117_fu_732_p2;
wire   [0:0] or_ln110_fu_776_p2;
wire   [0:0] xor_ln125_fu_814_p2;
wire   [0:0] and_ln125_fu_820_p2;
wire   [0:0] xor_ln125_1_fu_808_p2;
wire   [9:0] r257_1_fu_532_p3;
wire   [8:0] trunc_ln98_fu_772_p1;
wire   [8:0] add_ln150_fu_841_p2;
wire   [9:0] r514_1_fu_404_p3;
wire   [9:0] trunc_ln137_fu_832_p1;
wire   [8:0] q_load_4_cast_fu_905_p1;
wire   [8:0] q_load_2_cast_fu_901_p1;
wire   [8:0] q_load_5_cast_fu_925_p1;
wire   [8:0] q_load_7_cast_fu_929_p1;
wire   [8:0] tmp15_fu_936_p2;
wire   [9:0] tmp15_cast_fu_942_p1;
wire   [9:0] tmp_cast_fu_933_p1;
wire   [8:0] zext_ln136_fu_918_p1;
wire   [8:0] zext_ln140_fu_921_p1;
wire   [8:0] add_ln133_2_fu_952_p2;
wire   [9:0] zext_ln133_2_fu_958_p1;
wire   [9:0] zext_ln135_fu_915_p1;
wire   [9:0] shl_ln_fu_972_p3;
wire   [10:0] tmp3_fu_986_p3;
wire   [11:0] zext_ln133_1_fu_993_p1;
wire   [11:0] in_data_val_cast_fu_983_p1;
wire   [11:0] add_ln133_fu_997_p2;
wire   [11:0] zext_ln138_fu_979_p1;
wire   [11:0] zext_ln133_3_fu_1009_p1;
wire   [11:0] add_ln133_1_fu_1003_p2;
wire   [11:0] sum_fu_1012_p2;
wire   [0:0] and_ln131_fu_1034_p2;
wire   [7:0] next_data_1_fu_1018_p4;
wire   [7:0] next_data_3_fu_1028_p3;
wire   [0:0] xor_ln130_fu_1046_p2;
wire   [8:0] add_ln163_fu_1072_p2;
wire   [31:0] add_ln171_fu_1082_p2;
wire   [0:0] icmp_ln183_fu_1111_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 pending_data = 8'd0;
#0 pending_last = 1'd0;
#0 pending_valid = 1'd0;
#0 op_idx = 32'd0;
#0 wr = 32'd0;
#0 idx = 32'd0;
#0 first_frame = 1'd0;
end

denose_denoise_q_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 515 ),
    .AddressWidth( 10 ))
q_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(q_address0),
    .ce0(q_ce0),
    .q0(q_q0),
    .address1(q_address1),
    .ce1(q_ce1),
    .we1(q_we1),
    .d1(in_data_val),
    .q1(q_q1)
);

denose_denoise_rear_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 257 ),
    .AddressWidth( 9 ))
rear_frame_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rear_frame_address0),
    .ce0(rear_frame_ce0),
    .we0(rear_frame_we0),
    .d0(in_data_val),
    .q0(rear_frame_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        if ((in_last_read_read_fu_122_p2 == 1'd1)) begin
            idx <= 32'd0;
        end else if ((in_last_read_read_fu_122_p2 == 1'd0)) begin
            idx <= add_ln181_fu_1100_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd0) & (has_output_1_fu_800_p3 == 1'd0))) begin
        pending_last_flag_1_reg_250 <= and_ln92_fu_358_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        pending_last_flag_1_reg_250 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        pending_last_flag_2_reg_283 <= ap_phi_mux_pending_last_flag_1_phi_fu_253_p4;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd1))) begin
        pending_last_flag_2_reg_283 <= and_ln92_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd0) & (has_output_1_fu_800_p3 == 1'd0))) begin
        pending_last_new_1_reg_260 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        pending_last_new_1_reg_260 <= next_last_1_fu_1051_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        pending_last_new_2_reg_293 <= ap_phi_mux_pending_last_new_1_phi_fu_264_p4;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd1))) begin
        pending_last_new_2_reg_293 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd0) & (has_output_1_fu_800_p3 == 1'd0))) begin
        pending_valid_new_1_reg_271 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        pending_valid_new_1_reg_271 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        pending_valid_new_2_reg_305 <= ap_phi_mux_pending_valid_new_1_phi_fu_275_p4;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd1))) begin
        pending_valid_new_2_reg_305 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_317 <= q_q0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_317 <= q_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        if ((in_last_read_read_fu_122_p2 == 1'd1)) begin
            wr <= 32'd0;
        end else if ((in_last_read_read_fu_122_p2 == 1'd0)) begin
            wr <= select_ln183_fu_1116_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln101_reg_1220 <= add_ln101_fu_390_p2;
        and_ln116_1_reg_1274 <= and_ln116_1_fu_794_p2;
        has_output_1_reg_1279 <= has_output_1_fu_800_p3;
        icmp_ln112_reg_1264 <= icmp_ln112_fu_662_p2;
        icmp_ln117_reg_1269 <= icmp_ln117_fu_714_p2;
        next_last_reg_1297 <= next_last_fu_852_p2;
        or_ln125_reg_1283 <= or_ln125_fu_826_p2;
        or_ln130_reg_1312 <= or_ln130_fu_871_p2;
        out_valid_0_reg_1198[0] <= out_valid_0_fu_338_p1[0];
        pending_last_load_cast_reg_1193[0] <= pending_last_load_cast_fu_330_p1[0];
        r1_2_reg_1251 <= r1_2_fu_628_p3;
        r256_2_reg_1241 <= r256_2_fu_564_p3;
        r258_2_reg_1236 <= r258_2_fu_500_p3;
        r2_1_reg_1246 <= r2_1_fu_596_p3;
        r512_1_reg_1231 <= r512_1_fu_468_p3;
        r513_2_reg_1226 <= r513_2_fu_436_p3;
        select_ln110_reg_1307 <= select_ln110_fu_863_p3;
        trunc_ln110_reg_1259 <= trunc_ln110_fu_640_p1;
        zext_ln90_reg_1203[0] <= zext_ln90_fu_354_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln133_3_reg_1378 <= add_ln133_3_fu_962_p2;
        tmp154_reg_1373 <= tmp154_fu_946_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((in_last_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        first_frame <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        next_data_reg_1323 <= rear_frame_q0;
        q_load_1_reg_1328 <= q_q0;
        q_load_reg_1318 <= q_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        op_idx <= select_ln167_fu_1087_p3;
        pending_data <= next_data_4_fu_1038_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_pending_last_flag_2_phi_fu_286_p4 == 1'd1))) begin
        pending_last <= ap_phi_mux_pending_last_new_2_phi_fu_297_p4;
        pending_valid <= ap_phi_mux_pending_valid_new_2_phi_fu_309_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        q_load_3_reg_1343 <= q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_reg_1368 <= tmp_fu_909_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        ap_phi_mux_pending_last_flag_1_phi_fu_253_p4 = 1'd1;
    end else begin
        ap_phi_mux_pending_last_flag_1_phi_fu_253_p4 = pending_last_flag_1_reg_250;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        ap_phi_mux_pending_last_flag_2_phi_fu_286_p4 = ap_phi_mux_pending_last_flag_1_phi_fu_253_p4;
    end else begin
        ap_phi_mux_pending_last_flag_2_phi_fu_286_p4 = pending_last_flag_2_reg_283;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        ap_phi_mux_pending_last_new_1_phi_fu_264_p4 = next_last_1_fu_1051_p2;
    end else begin
        ap_phi_mux_pending_last_new_1_phi_fu_264_p4 = pending_last_new_1_reg_260;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        ap_phi_mux_pending_last_new_2_phi_fu_297_p4 = ap_phi_mux_pending_last_new_1_phi_fu_264_p4;
    end else begin
        ap_phi_mux_pending_last_new_2_phi_fu_297_p4 = pending_last_new_2_reg_293;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0) & (has_output_1_reg_1279 == 1'd1))) begin
        ap_phi_mux_pending_valid_new_1_phi_fu_275_p4 = 1'd1;
    end else begin
        ap_phi_mux_pending_valid_new_1_phi_fu_275_p4 = pending_valid_new_1_reg_271;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        ap_phi_mux_pending_valid_new_2_phi_fu_309_p4 = ap_phi_mux_pending_valid_new_1_phi_fu_275_p4;
    end else begin
        ap_phi_mux_pending_valid_new_2_phi_fu_309_p4 = pending_valid_new_2_reg_305;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        q_address0 = zext_ln128_fu_968_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        q_address0 = zext_ln140_1_fu_897_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        q_address0 = zext_ln138_1_fu_889_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        q_address0 = zext_ln135_1_fu_881_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        q_address0 = zext_ln133_fu_858_p1;
    end else begin
        q_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        q_address1 = zext_ln161_fu_1063_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        q_address1 = zext_ln139_fu_893_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        q_address1 = zext_ln136_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        q_address1 = zext_ln134_fu_877_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        q_address1 = zext_ln137_fu_836_p1;
    end else begin
        q_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        q_ce0 = 1'b1;
    end else begin
        q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        q_ce1 = 1'b1;
    end else begin
        q_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        q_we1 = 1'b1;
    end else begin
        q_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rear_frame_address0 = zext_ln163_fu_1077_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rear_frame_address0 = zext_ln150_fu_847_p1;
    end else begin
        rear_frame_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        rear_frame_ce0 = 1'b1;
    end else begin
        rear_frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1067_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (or_ln125_reg_1283 == 1'd0))) begin
        rear_frame_we0 = 1'b1;
    end else begin
        rear_frame_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (or_ln125_fu_826_p2 == 1'd0) & (has_output_1_fu_800_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((or_ln125_fu_826_p2 == 1'd1) | (has_output_1_fu_800_p3 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_fu_390_p2 = (wr + 32'd1);

assign add_ln103_fu_462_p2 = (trunc_ln101_fu_372_p1 + 10'd3);

assign add_ln105_fu_526_p2 = (trunc_ln101_fu_372_p1 + 10'd258);

assign add_ln107_fu_590_p2 = ($signed(trunc_ln101_fu_372_p1) + $signed(10'd513));

assign add_ln117_fu_720_p2 = ($signed(idx) + $signed(32'd4294967039));

assign add_ln133_1_fu_1003_p2 = (add_ln133_fu_997_p2 + zext_ln138_fu_979_p1);

assign add_ln133_2_fu_952_p2 = (zext_ln136_fu_918_p1 + zext_ln140_fu_921_p1);

assign add_ln133_3_fu_962_p2 = (zext_ln133_2_fu_958_p1 + zext_ln135_fu_915_p1);

assign add_ln133_fu_997_p2 = (zext_ln133_1_fu_993_p1 + in_data_val_cast_fu_983_p1);

assign add_ln150_fu_841_p2 = ($signed(trunc_ln98_fu_772_p1) + $signed(9'd257));

assign add_ln163_fu_1072_p2 = ($signed(trunc_ln110_reg_1259) + $signed(9'd257));

assign add_ln171_fu_1082_p2 = (op_idx + 32'd1);

assign add_ln181_fu_1100_p2 = (idx + 32'd1);

assign and_ln110_1_fu_782_p2 = (icmp_ln110_fu_644_p2 & icmp_ln110_1_fu_650_p2);

assign and_ln110_fu_656_p2 = (icmp_ln110_fu_644_p2 & icmp_ln110_1_fu_650_p2);

assign and_ln116_1_fu_794_p2 = (xor_ln110_fu_788_p2 & and_ln116_fu_698_p2);

assign and_ln116_fu_698_p2 = (icmp_ln116_fu_676_p2 & icmp_ln116_1_fu_692_p2);

assign and_ln125_fu_820_p2 = (xor_ln125_fu_814_p2 & pending_valid);

assign and_ln131_fu_1034_p2 = (icmp_ln117_reg_1269 & and_ln116_1_reg_1274);

assign and_ln92_fu_358_p2 = (pending_valid & out_ready);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_return_0 = zext_ln90_reg_1203;

assign ap_return_1 = pending_data;

assign ap_return_2 = pending_last_load_cast_reg_1193;

assign ap_return_3 = out_valid_0_reg_1198;

assign has_output_1_fu_800_p3 = ((and_ln116_1_fu_794_p2[0:0] == 1'b1) ? or_ln117_fu_732_p2 : or_ln110_fu_776_p2);

assign has_output_fu_758_p2 = (icmp_ln121_fu_752_p2 & first_frame);

assign icmp_ln110_1_fu_650_p2 = (($signed(idx) < $signed(32'd514)) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_644_p2 = (($signed(idx) > $signed(32'd256)) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_662_p2 = ((idx == 32'd257) ? 1'b1 : 1'b0);

assign icmp_ln116_1_fu_692_p2 = (($signed(tmp_9_fu_682_p4) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign icmp_ln116_fu_676_p2 = (($signed(idx) > $signed(32'd513)) ? 1'b1 : 1'b0);

assign icmp_ln117_1_fu_726_p2 = ((op_idx == add_ln117_fu_720_p2) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_714_p2 = ((tmp_10_fu_704_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_752_p2 = (($signed(tmp_11_fu_742_p4) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_1067_p2 = (($signed(idx) > $signed(32'd65278)) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_1111_p2 = ((add_ln101_reg_1220 == 32'd515) ? 1'b1 : 1'b0);

assign in_data_val_cast_fu_983_p1 = in_data_val;

assign in_last_read_read_fu_122_p2 = in_last;

assign next_data_1_fu_1018_p4 = {{sum_fu_1012_p2[11:4]}};

assign next_data_3_fu_1028_p3 = ((or_ln130_reg_1312[0:0] == 1'b1) ? q_q0 : next_data_reg_1323);

assign next_data_4_fu_1038_p3 = ((and_ln131_fu_1034_p2[0:0] == 1'b1) ? next_data_1_fu_1018_p4 : next_data_3_fu_1028_p3);

assign next_last_1_fu_1051_p2 = (xor_ln130_fu_1046_p2 & next_last_reg_1297);

assign next_last_fu_852_p2 = ((output_idx_2_fu_764_p3 == 32'd65535) ? 1'b1 : 1'b0);

assign or_ln110_fu_776_p2 = (has_output_fu_758_p2 | and_ln110_fu_656_p2);

assign or_ln117_fu_732_p2 = (icmp_ln117_fu_714_p2 | icmp_ln117_1_fu_726_p2);

assign or_ln125_fu_826_p2 = (xor_ln125_1_fu_808_p2 | and_ln125_fu_820_p2);

assign or_ln130_fu_871_p2 = (and_ln116_fu_698_p2 | and_ln110_fu_656_p2);

assign or_ln90_fu_348_p2 = (xor_ln90_fu_342_p2 | out_ready);

assign out_valid_0_fu_338_p1 = pending_valid;

assign output_idx_1_fu_668_p3 = ((icmp_ln112_fu_662_p2[0:0] == 1'b1) ? 32'd0 : op_idx);

assign output_idx_2_fu_764_p3 = ((and_ln110_fu_656_p2[0:0] == 1'b1) ? output_idx_1_fu_668_p3 : op_idx);

assign pending_last_load_cast_fu_330_p1 = pending_last;

assign q_load_2_cast_fu_901_p1 = reg_317;

assign q_load_4_cast_fu_905_p1 = q_q1;

assign q_load_5_cast_fu_925_p1 = reg_317;

assign q_load_7_cast_fu_929_p1 = q_q0;

assign r1_1_fu_622_p2 = ($signed(trunc_ln101_fu_372_p1) + $signed(10'd514));

assign r1_2_fu_628_p3 = ((tmp_8_fu_614_p3[0:0] == 1'b1) ? r1_1_fu_622_p2 : trunc_ln108_fu_610_p1);

assign r1_fu_604_p2 = ($signed(wr) + $signed(32'd4294967295));

assign r256_1_fu_558_p2 = (trunc_ln101_fu_372_p1 + 10'd259);

assign r256_2_fu_564_p3 = ((tmp_6_fu_550_p3[0:0] == 1'b1) ? r256_1_fu_558_p2 : trunc_ln106_fu_546_p1);

assign r256_fu_540_p2 = ($signed(wr) + $signed(32'd4294967040));

assign r257_1_fu_532_p3 = ((tmp_5_fu_518_p3[0:0] == 1'b1) ? add_ln105_fu_526_p2 : trunc_ln105_fu_514_p1);

assign r257_fu_508_p2 = ($signed(wr) + $signed(32'd4294967039));

assign r258_1_fu_494_p2 = (trunc_ln101_fu_372_p1 + 10'd257);

assign r258_2_fu_500_p3 = ((tmp_4_fu_486_p3[0:0] == 1'b1) ? r258_1_fu_494_p2 : trunc_ln104_fu_482_p1);

assign r258_fu_476_p2 = ($signed(wr) + $signed(32'd4294967038));

assign r2_1_fu_596_p3 = ((tmp_7_fu_582_p3[0:0] == 1'b1) ? add_ln107_fu_590_p2 : trunc_ln107_fu_578_p1);

assign r2_fu_572_p2 = ($signed(wr) + $signed(32'd4294967294));

assign r512_1_fu_468_p3 = ((tmp_3_fu_454_p3[0:0] == 1'b1) ? add_ln103_fu_462_p2 : trunc_ln103_fu_450_p1);

assign r512_fu_444_p2 = ($signed(wr) + $signed(32'd4294966784));

assign r513_1_fu_430_p2 = (trunc_ln101_fu_372_p1 + 10'd2);

assign r513_2_fu_436_p3 = ((tmp_2_fu_422_p3[0:0] == 1'b1) ? r513_1_fu_430_p2 : trunc_ln102_fu_418_p1);

assign r513_fu_412_p2 = ($signed(wr) + $signed(32'd4294966783));

assign r514_1_fu_404_p3 = ((tmp_1_fu_382_p3[0:0] == 1'b1) ? trunc_ln101_1_fu_396_p1 : trunc_ln101_2_fu_400_p1);

assign r514_fu_376_p2 = ($signed(wr) + $signed(32'd4294966782));

assign select_ln110_fu_863_p3 = ((and_ln110_fu_656_p2[0:0] == 1'b1) ? trunc_ln137_fu_832_p1 : r257_1_fu_532_p3);

assign select_ln167_fu_1087_p3 = ((icmp_ln112_reg_1264[0:0] == 1'b1) ? 32'd1 : add_ln171_fu_1082_p2);

assign select_ln183_fu_1116_p3 = ((icmp_ln183_fu_1111_p2[0:0] == 1'b1) ? 32'd0 : add_ln101_reg_1220);

assign shl_ln_fu_972_p3 = {{q_load_reg_1318}, {2'd0}};

assign sum_fu_1012_p2 = (zext_ln133_3_fu_1009_p1 + add_ln133_1_fu_1003_p2);

assign tmp154_fu_946_p2 = (tmp15_cast_fu_942_p1 + tmp_cast_fu_933_p1);

assign tmp15_cast_fu_942_p1 = tmp15_fu_936_p2;

assign tmp15_fu_936_p2 = (q_load_5_cast_fu_925_p1 + q_load_7_cast_fu_929_p1);

assign tmp3_fu_986_p3 = {{tmp154_reg_1373}, {1'd0}};

assign tmp_10_fu_704_p4 = {{idx[7:1]}};

assign tmp_11_fu_742_p4 = {{op_idx[31:16]}};

assign tmp_1_fu_382_p3 = r514_fu_376_p2[32'd31];

assign tmp_2_fu_422_p3 = r513_fu_412_p2[32'd31];

assign tmp_3_fu_454_p3 = r512_fu_444_p2[32'd31];

assign tmp_4_fu_486_p3 = r258_fu_476_p2[32'd31];

assign tmp_5_fu_518_p3 = r257_fu_508_p2[32'd31];

assign tmp_6_fu_550_p3 = r256_fu_540_p2[32'd31];

assign tmp_7_fu_582_p3 = r2_fu_572_p2[32'd31];

assign tmp_8_fu_614_p3 = r1_fu_604_p2[32'd31];

assign tmp_9_fu_682_p4 = {{idx[31:16]}};

assign tmp_cast_fu_933_p1 = tmp_reg_1368;

assign tmp_fu_909_p2 = (q_load_4_cast_fu_905_p1 + q_load_2_cast_fu_901_p1);

assign trunc_ln101_1_fu_396_p1 = add_ln101_fu_390_p2[9:0];

assign trunc_ln101_2_fu_400_p1 = r514_fu_376_p2[9:0];

assign trunc_ln101_fu_372_p1 = wr[9:0];

assign trunc_ln102_fu_418_p1 = r513_fu_412_p2[9:0];

assign trunc_ln103_fu_450_p1 = r512_fu_444_p2[9:0];

assign trunc_ln104_fu_482_p1 = r258_fu_476_p2[9:0];

assign trunc_ln105_fu_514_p1 = r257_fu_508_p2[9:0];

assign trunc_ln106_fu_546_p1 = r256_fu_540_p2[9:0];

assign trunc_ln107_fu_578_p1 = r2_fu_572_p2[9:0];

assign trunc_ln108_fu_610_p1 = r1_fu_604_p2[9:0];

assign trunc_ln110_fu_640_p1 = idx[8:0];

assign trunc_ln137_fu_832_p1 = output_idx_2_fu_764_p3[9:0];

assign trunc_ln98_fu_772_p1 = output_idx_2_fu_764_p3[8:0];

assign xor_ln110_fu_788_p2 = (1'd1 ^ and_ln110_1_fu_782_p2);

assign xor_ln125_1_fu_808_p2 = (in_valid ^ 1'd1);

assign xor_ln125_fu_814_p2 = (out_ready ^ 1'd1);

assign xor_ln130_fu_1046_p2 = (or_ln130_reg_1312 ^ 1'd1);

assign xor_ln90_fu_342_p2 = (pending_valid ^ 1'd1);

assign zext_ln128_fu_968_p1 = select_ln110_reg_1307;

assign zext_ln133_1_fu_993_p1 = tmp3_fu_986_p3;

assign zext_ln133_2_fu_958_p1 = add_ln133_2_fu_952_p2;

assign zext_ln133_3_fu_1009_p1 = add_ln133_3_reg_1378;

assign zext_ln133_fu_858_p1 = r514_1_fu_404_p3;

assign zext_ln134_fu_877_p1 = r513_2_reg_1226;

assign zext_ln135_1_fu_881_p1 = r512_1_reg_1231;

assign zext_ln135_fu_915_p1 = q_load_1_reg_1328;

assign zext_ln136_1_fu_885_p1 = r258_2_reg_1236;

assign zext_ln136_fu_918_p1 = q_load_3_reg_1343;

assign zext_ln137_fu_836_p1 = r257_1_fu_532_p3;

assign zext_ln138_1_fu_889_p1 = r256_2_reg_1241;

assign zext_ln138_fu_979_p1 = shl_ln_fu_972_p3;

assign zext_ln139_fu_893_p1 = r2_1_reg_1246;

assign zext_ln140_1_fu_897_p1 = r1_2_reg_1251;

assign zext_ln140_fu_921_p1 = q_q1;

assign zext_ln150_fu_847_p1 = add_ln150_fu_841_p2;

assign zext_ln161_fu_1063_p1 = wr;

assign zext_ln163_fu_1077_p1 = add_ln163_fu_1072_p2;

assign zext_ln90_fu_354_p1 = or_ln90_fu_348_p2;

always @ (posedge ap_clk) begin
    pending_last_load_cast_reg_1193[31:1] <= 31'b0000000000000000000000000000000;
    out_valid_0_reg_1198[31:1] <= 31'b0000000000000000000000000000000;
    zext_ln90_reg_1203[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //denose_denoise
